# Generated by Django 5.0.1 on 2024-03-31 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='nombreAlumno',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nombreCurso',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='legajo_p',
            new_name='legajo',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='nombreProfesor',
            new_name='nombre',
        ),
    ]
